version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.12"
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - pwd
      - ls
      - sam validate --template-file devops/template.yaml
      - mkdir -p layers/common/psycopg/python
      - pip install psycopg[binary] -t layers/common/psycopg/python/

  build:
    commands:
      - sam build --template-file devops/template.yaml
      - ls .aws-sam/build/
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file ./packaged.yaml --s3-bucket $SAM_ARTIFACTS_BUCKET --s3-prefix chat-management-api --region ap-south-1
      - echo "checking packaged.yaml location"
      - ls -la packaged.yaml
      - pwd
  post_build:
    commands:
      - echo "Current directory"
      - pwd
      - echo "All files in current directory"
      - find . -name "packaged.yaml"
      - ls -la

      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          echo "Build succeeded - packaged.yaml ready for deploy"
        else
          echo "Build failed"
        fi

artifacts:
  files:
    - "**/*"
  discard-paths: no