AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Chat Management API

Parameters:
  Stage:
    Type: String
    Default: dev

  DatabaseUrl:
    Type: String

  SecretKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: python3.12
    #Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        STAGE: !Ref Stage
        DATABASE_URL: !Ref DatabaseUrl
        SECRET_KEY: !Ref SecretKey

Resources:

  PsycopgLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "psycopg-layer-${Stage}"
      ContentUri: ../layers/common
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "chat-management-userpool-${Stage}"

      UsernameAttributes:
        - email

      AutoVerifiedAttributes:
        - email

      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "chat-management-client-${Stage}"
      UserPoolId: !Ref CognitoUserPool

      GenerateSecret: false

      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ChatApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "chat-management-api-${Stage}"
      StageName: !Ref Stage
      OpenApiVersion: 3.0.1

      Auth:
        DefaultAuthorizer: CognitoAuthorizer

        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-auth-lambda-${Stage}"

      CodeUri: ../app/services/users

      Handler: cognito_lambda_handler.lambda_handler
      Timeout: 10

      Layers:
        - !Ref PsycopgLayer

      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          CLIENT_ID: !Ref CognitoUserPoolClient

      Policies:
        - AWSLambdaBasicExecutionRole

        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
                - cognito-idp:AdminConfirmSignUp
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:GlobalSignOut
              Resource: !GetAtt CognitoUserPool.Arn

      Events:

        Login:
          Type: Api
          Properties:
            Path: /api/v1/auth/login
            Method: post
            RestApiId: !Ref ChatApi
            Auth:
              Authorizer: NONE

        CreateUser:
          Type: Api
          Properties:
            Path: /api/v1/auth/users
            Method: post
            RestApiId: !Ref ChatApi
            Auth:
              Authorizer: NONE

        GetUser:
          Type: Api
          Properties:
            Path: /api/v1/auth/users/{user_id}
            Method: get
            RestApiId: !Ref ChatApi

        Verify:
          Type: Api
          Properties:
            Path: /api/v1/auth/verify
            Method: post
            RestApiId: !Ref ChatApi
            Auth:
              Authorizer: NONE

  DirectChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-direct-chat-lambda-${Stage}"
      CodeUri: ../app/services/direct_chat
      Handler: direct_chat_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ListDirectChat:
          Type: Api
          Properties:
            Path: /api/v1/direct-chats
            Method: get
            RestApiId: !Ref ChatApi

        CreateDirectChat:
          Type: Api
          Properties:
            Path: /api/v1/direct-chats
            Method: post
            RestApiId: !Ref ChatApi

  DirectMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-direct-message-lambda-${Stage}"
      CodeUri: ../app/services/direct_message
      Handler: direct_message_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        ListMessage:
          Type: Api
          Properties:
            Path: /api/v1/direct-chats/{chat_id}/messages
            Method: get
            RestApiId: !Ref ChatApi

        CreateMessage:
          Type: Api
          Properties:
            Path: /api/v1/direct-chats/{chat_id}/messages
            Method: post
            RestApiId: !Ref ChatApi

        DeleteMessage:
          Type: Api
          Properties:
            Path: /api/v1/direct-chats/{chat_id}/messages/{message_id}
            Method: delete
            RestApiId: !Ref ChatApi
  
  GroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-groups-lambda-${Stage}"
      CodeUri: ../app/services/groups
      Handler: groups_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        ListGroups:
          Type: Api
          Properties:
            Path: /api/v1/groups
            Method: get
            RestApiId: !Ref ChatApi

        CreateGroup:
          Type: Api
          Properties:
            Path: /api/v1/groups
            Method: post
            RestApiId: !Ref ChatApi

        GetGroup:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}
            Method: get
            RestApiId: !Ref ChatApi

        DeleteGroup:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}
            Method: delete
            RestApiId: !Ref ChatApi

        UpdateGroupSettings:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}/settings
            Method: patch
            RestApiId: !Ref ChatApi

  GroupMembersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-group-members-lambda-${Stage}"
      CodeUri: ../app/services/group_member
      Handler: groupMember_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        ListMembers:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}/members
            Method: get
            RestApiId: !Ref ChatApi

        AddMember:
            Type: Api
            Properties:
              Path: /api/v1/groups/{group_id}/members
              Method: post
              RestApiId: !Ref ChatApi

        RemoveMember:
            Type: Api
            Properties:
              Path: /api/v1/groups/{group_id}/members/{user_id}
              Method: delete
              RestApiId: !Ref ChatApi

  GroupMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-group-message-lambda-${Stage}"
      CodeUri: ../app/services/group_messages
      Handler: group_message_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        ListGroupMessages:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}/messages
            Method: get
            RestApiId: !Ref ChatApi

        CreateGroupMessage:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}/messages
            Method: post
            RestApiId: !Ref ChatApi

        DeleteGroupMessage:
          Type: Api
          Properties:
            Path: /api/v1/groups/{group_id}/messages/{message_id}
            Method: delete
            RestApiId: !Ref ChatApi

  MessageDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chat-message-delivery-lambda-${Stage}"
      CodeUri: ../app/services/message_delivery_status
      Handler: message_delivery_lambda.lambda_handler
      Timeout: 15
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        UpdateDeliveryStatus:
          Type: Api
          Properties:
            Path: /api/v1/message/delivery/{message_id}
            Method: patch
            RestApiId: !Ref ChatApi

        GetDeliveryReport:
          Type: Api
          Properties:
            Path: /api/v1/message/delivery/{message_id}/report
            Method: get
            RestApiId: !Ref ChatApi

Outputs:

  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ChatApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref CognitoUserPoolClient