AWSTemplateFormatVersion: '2010-09-09'
Resources:

  ChatUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "ChatUserPool"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email

  ChatUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ChatUserPool
      ClientName: "Chat-User-Pool-Client"
      GenerateSecret: false
      

  AuthLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: rest-auth-lambda-role

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  AuthLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: rest-auth-lambda

      Runtime: python3.12

      Handler: index.lambda_handler

      Role: !GetAtt AuthLambdaRole.Arn

      Timeout: 10

      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "body": "Hello from Lambda"
              }

  AuthRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestAuthApi

  RegisterResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AuthRestApi
      ParentId: !GetAtt AuthRestApi.RootResourceId
      PathPart: register

  RegisterMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AuthRestApi
      ResourceId: !Ref RegisterResource
      HttpMethod: POST
      AuthorizationType: NONE

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthLambda.Arn}/invocations

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthRestApi}/*

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RegisterMethod
    Properties:
      RestApiId: !Ref AuthRestApi
      StageName: dev